version: "3.8"

services:
  backend:
    build:
      context: ./backend
    ports:
      - "4000:4000" # Backend chạy trên cổng 4000
    volumes:
      - ./backend:/app
    depends_on:
      - mongodb

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000" # Frontend chạy trên cổng 3000 (React app)
    volumes:
      - ./frontend:/app
      - /app/node_modules
    stdin_open: true
    tty: true

  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
