version: '3.8'
services:
  backend:
    build: .
    ports:
      - "4000:4000"
    depends_on:
      - mongodb
    environment:
      - MONGO_URL=mongodb://mongodb:27017/BlockChain

  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
